---
sonobuoy-config:
  driver: Job
  plugin-name: helloworld
  result-type: helloworld
spec:
  env:
  - name: E2E_FOCUS
    value: Pods should be submitted and removed
  image: quay.io/lander2k2/sonobuoy-test-plugin
  imagePullPolicy: Always
  name: test
  volumeMounts:
  - mountPath: /tmp/results
    name: results
    readOnly: false

